### PR TITLE
docs: Add 2023-09-07 meeting notes

### LINKED ISSUE #452: TSC meeting 07-September-2023
# Time

UTC Thu 07-Sep-2023 20:00:
- Los Angeles: Thu 07-Sep-2023 13:00
- Chicago: Thu 07-Sep-2023 15:00
- New York: Thu 07-Sep-2023 16:00
- Madrid: Thu 07-Sep-2023 22:00
- Moscow: Thu 07-Sep-2023 23:00
- Tokyo: Fri 08-Sep-2023 05:00
- Sydney: Fri 08-Sep-2023 06:00

# Location

https://eslint.org/chat/tsc-meetings

# Agenda

Extracted from:

* Issues and pull requests from the ESLint organization with the ["tsc agenda" label](https://github.com/issues?utf8=%E2%9C%93&q=org%3Aeslint+label%3A%22tsc+agenda%22)
* Comments on this issue

# Invited

- Nicholas C. Zakas (@nzakas) - TSC
- Milos Djermanovic (@mdjermanovic) - TSC

# Public participation

Anyone is welcome to attend the meeting as observers. We ask that you refrain from interrupting the meeting once it begins and only participate if invited to do so.

### PR DESCRIPTION
**Pull request by sam3k**
Closes #452

### CODE REVIEW

**Comment by sam3k** [comment]
Nicholas, Milos, I've added the convos for issue [#17524](https://github.com/eslint/eslint/issues/17524) and for the v9 release strategy. If it is too much, I'll be happy to remove it.

**Comment by nzakas** [comment]
Thanks, yeah, I think it's too much. Can you just write a summary of the conversation and result? People can always look at the transcript if they want the full conversation.

**Comment by sam3k** [comment]
> Thanks, yeah, I think it's too much. Can you just write a summary of the conversation and result? People can always look at the transcript if they want the full conversation.

Will do.

**Comment by sam3k** [comment]
@nzakas, I've gone ahead and remove all convos and summarize. Let me know if there is anything else you would like me to update. 👍

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks! Leaving open for @nzakas to review.

**Review by nzakas — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
