### PR TITLE
21July2016 meeting notes (closes #3)

### LINKED ISSUE #3: TSC Meeting 21-Jul-2016
# Time

UTC Thu 21-Jul-2016 20:00:

* San Francisco: Thu 21-Jul-2016 13:00
* New York: Thu 21-Jul-2016 16:00
* Madrid: Thu 21-Jul-2016 22:00
* Moscow: Thu 21-Jul-2016 23:00
* Sydney: Fri 22-Jul-2016 06:00
* Tokyo: Fri 22-Jul-2016 05:00

# Location

https://gitter.im/eslint/tsc-meetings

# Agenda

Extracted from "tsc agenda" labelled issues and pull requests from the ESLint org prior to the meeting and comments on this issue.

# Invited

* Nicholas Zakas (@nzakas) - TSC
* Ilya Volodin (@ilyavolodin) - TSC
* Brandon Mills (@btmills) - TSC
* Gyandeep Singh (@gyandeeps) - TSC
* Toru Nagashima (@mysticatea) - TSC
* Alberto Rodríguez (@alberto) - TSC

# Public participation

Anyone is welcome to attend the meeting as observers. We ask that you refrain from interrupting the meeting once it begins and only participate if invited to do so.

### PR DESCRIPTION
**Pull request by IanVS**
Note: I've changed the naming format of the notes file to use MM-DD-YYYY to make them sort more cleanly.  I did not change the filename of the previous notes document, and I'm happy to change back to that format if desired.

### CODE REVIEW

**Comment by nzakas** [comment]
The trouble with the filename change is that internationally, some use mm-dd-yyyy while others use dd-mm-yyyy, so it's not 100% clear in all cases to all people. I don't mind changing the format, but we do need text for the month name to avoid ambiguity internationally.

**Comment by IanVS** [comment]
How about ISO 8601 (YYYY-MM-DD)?  I think that's standard enough to avoid confusion (plus it's hard to mistake "21" as a month).

**Comment by nzakas** [comment]
We won't always have meetings on double-digit days :)

ISO 8601 sounds good

**Comment by IanVS** [comment]
For single digit months or days, we can add a leading zero.  :)

**Comment by IanVS** [comment]
@nzakas I updated both filenames.

**Comment by nzakas** [comment]
Thanks!

**Pull request merged**
