### PR TITLE
Add 2022-06-16 meeting notes (closes #353)

### LINKED ISSUE #353: TSC meeting 16-June-2022
# Time

UTC Thu 16-Jun-2022 20:00:
- Los Angeles: Thu 16-Jun-2022 13:00
- Chicago: Thu 16-Jun-2022 15:00
- New York: Thu 16-Jun-2022 16:00
- Madrid: Thu 16-Jun-2022 22:00
- Moscow: Thu 16-Jun-2022 23:00
- Tokyo: Fri 17-Jun-2022 05:00
- Sydney: Fri 17-Jun-2022 06:00

# Location

https://eslint.org/chat/tsc-meetings

# Agenda

Extracted from:

* Issues and pull requests from the ESLint organization with the ["tsc agenda" label](https://github.com/issues?utf8=%E2%9C%93&q=org%3Aeslint+label%3A%22tsc+agenda%22)
* Comments on this issue

# Invited

- Nicholas C. Zakas (@nzakas) - TSC
- Brandon Mills (@btmills) - TSC
- Milos Djermanovic (@mdjermanovic) - TSC

# Public participation

Anyone is welcome to attend the meeting as observers. We ask that you refrain from interrupting the meeting once it begins and only participate if invited to do so.

### PR DESCRIPTION
**Pull request by btmills**

### CODE REVIEW

**Review by mdjermanovic — DISMISSED** [review]

**Comment by mdjermanovic** [comment]
I'm not sure what has changed recently so we're getting errors on `npm install` in the lint job now.

**Comment by btmills** [comment]
Oh wow, I recognize that installation failure! I just spent a while debugging two separate behavior changes in recent versions of npm for https://github.com/eslint/eslint-plugin-markdown/pull/206. The Markdown plugin's test setup is a little weird, so I figured we were somehow hitting unsupported behavior. That this repository is also failing leads me to believe there was a regression or intentional breaking change in npm 8.6.0. (8.5.5 shipped with Node 16.12.0. Node 16.12.1 upgraded to npm 8.11.0, but I narrowed down that breakage further to working on Node 16.12.1 with npm 8.5.5 and failing on Node 16.12.1 with npm 8.6.0.)

**Comment by btmills** [comment]
I haven't narrowed it down to a specific commit in npm 8.6.0, but the newly-reported conflict is at least accurate, and I resolved the conflict in https://github.com/eslint/tsc-meetings/pull/357. Once that's in, I'll rebase this on `main`.

**Comment by btmills** [comment]
Rebased, and CI passed! No changes to this diff, but GitHub dismissed the approving review anyway, so re-requesting.

**Pull request merged**
